services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - LLAMA_HOSTS=http://ollama:11434
  
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    deploy: # Comment this section to use CPU
      resources:
        reservations:
          devices:
            - driver: nvidia # Requires NVIDIA container runtime
              count: all
              capabilities: [gpu]

volumes:
  ollama: